name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push frontend image
        run: |
          docker build -t your-dockerhub-username/frontend:latest ./frontend
          - name: Log in to Azure Container Registry
            uses: azure/docker-login@v1
            with:
              login-server: your-azure-registry-name.azurecr.io
              username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
              password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

          - name: Build and push frontend image
            run: |
              docker build -t your-azure-registry-name.azurecr.io/student-frontend:latest ./frontend
              docker push your-azure-registry-name.azurecr.io/student-frontend:latest
      - name: Build and push backend image
        run: |
          docker build -t your-azure-registry-name.azurecr.io/student-backend:latest ./backend
          docker push your-azure-registry-name.azurecr.io/student-backend:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: myWebApp
          slot-name: production
          images: |
            your-azure-registry-name.azurecr.io/frontend:latest
            your-azure-registry-name.azurecr.io/backend:latest
