name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/student-frontend:latest ./frontend
          docker push ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/student-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/student-backend:latest ./backend
          docker push ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/student-backend:latest

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App Backend
            uses: azure/webapps-deploy@v2
            with:
              app-name: student-app-backend
              images: ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/student-backend:latest
              
       - name: Deploy to Azure Web App Frontend
            uses: azure/webapps-deploy@v2
            with:
              app-name: student-app-frontend
              images: ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/student-frontend:latest
